# Generated by Django 4.2.30 on 2026-05-12 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('favicon_url', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('tracking_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('tracking_script_version', models.CharField(default='1.0.0', max_length=10)),
                ('is_tracking_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='Additional allowed domains for tracking (subdomains, staging, etc.)')),
                ('exclude_ips', models.JSONField(blank=True, default=list, help_text='IP addresses to exclude from tracking (e.g., internal team)')),
                ('anonymize_ips', models.BooleanField(default=True)),
                ('gdpr_mode', models.BooleanField(default=False)),
                ('respect_dnt', models.BooleanField(default=True)),
                ('filter_bots', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'db_table': 'websites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSharedAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('admin', 'Admin')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_access', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_page_views', models.BooleanField(default=True)),
                ('track_scroll_depth', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('track_forms', models.BooleanField(default=True)),
                ('track_outbound_links', models.BooleanField(default=True)),
                ('track_file_downloads', models.BooleanField(default=True)),
                ('track_404_errors', models.BooleanField(default=True)),
                ('custom_events_enabled', models.BooleanField(default=True)),
                ('session_recording_enabled', models.BooleanField(default=False)),
                ('batch_size', models.IntegerField(default=10)),
                ('flush_interval_ms', models.IntegerField(default=5000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script_config', to='websites.website')),
            ],
            options={
                'db_table': 'tracking_scripts',
            },
        ),
        migrations.CreateModel(
            name='WebsiteMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='view', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_memberships', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='websites.website')),
            ],
            options={
                'db_table': 'website_members',
                'unique_together': {('website', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['tracking_id'], name='websites_trackin_be937e_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['owner', 'status'], name='websites_owner_i_595c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['domain'], name='websites_domain_9fabc6_idx'),
        ),
    ]
