# Generated by Django 4.2.30 on 2026-05-12 15:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=20)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('screen_width', models.IntegerField(blank=True, null=True)),
                ('screen_height', models.IntegerField(blank=True, null=True)),
                ('viewport_width', models.IntegerField(blank=True, null=True)),
                ('viewport_height', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('visit_count', models.IntegerField(default=1)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='websites.website')),
            ],
            options={
                'db_table': 'analytics_visitors',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrer_url', models.TextField(blank=True)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('entry_type', models.CharField(choices=[('direct', 'Direct'), ('referral', 'Referral'), ('search', 'Search Engine'), ('social', 'Social Media'), ('email', 'Email'), ('paid', 'Paid Ads'), ('other', 'Other')], default='direct', max_length=20)),
                ('entry_page', models.TextField(blank=True)),
                ('exit_page', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_bounce', models.BooleanField(default=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.visitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='websites.website')),
            ],
            options={
                'db_table': 'analytics_sessions',
            },
        ),
        migrations.CreateModel(
            name='RealtimeVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_page', models.TextField(blank=True)),
                ('current_page_title', models.CharField(blank=True, max_length=500)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('last_active_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_records', to='analytics.visitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_visitors', to='websites.website')),
            ],
            options={
                'db_table': 'analytics_realtime_visitors',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(db_index=True)),
                ('path', models.TextField(db_index=True)),
                ('hostname', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('query_params', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('time_on_page', models.IntegerField(default=0, help_text='Seconds spent on page')),
                ('scroll_depth', models.IntegerField(default=0, help_text='Max scroll depth percentage (0-100)')),
                ('is_exit_page', models.BooleanField(default=False)),
                ('is_entry_page', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='websites.website')),
            ],
            options={
                'db_table': 'analytics_page_views',
            },
        ),
        migrations.CreateModel(
            name='MonthlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_visitors', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('traffic_sources', models.JSONField(default=dict)),
                ('top_pages', models.JSONField(default=list)),
                ('top_countries', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_analytics', to='websites.website')),
            ],
            options={
                'db_table': 'analytics_monthly',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('form_submit', 'Form Submission'), ('scroll', 'Scroll'), ('video_play', 'Video Play'), ('video_complete', 'Video Complete'), ('download', 'File Download'), ('outbound_link', 'Outbound Link'), ('custom', 'Custom Event'), ('error_404', '404 Error'), ('conversion', 'Conversion')], db_index=True, max_length=30)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('element_tag', models.CharField(blank=True, max_length=50)),
                ('element_id', models.CharField(blank=True, max_length=255)),
                ('element_class', models.CharField(blank=True, max_length=500)),
                ('element_text', models.CharField(blank=True, max_length=255)),
                ('element_href', models.TextField(blank=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('page_view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.pageview')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='websites.website')),
            ],
            options={
                'db_table': 'analytics_events',
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_visitors', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('returning_visitors', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_pages_per_session', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_scroll_depth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('traffic_sources', models.JSONField(default=dict)),
                ('top_pages', models.JSONField(default=list)),
                ('top_countries', models.JSONField(default=list)),
                ('device_breakdown', models.JSONField(default=dict)),
                ('browser_breakdown', models.JSONField(default=dict)),
                ('hourly_breakdown', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='websites.website')),
            ],
            options={
                'db_table': 'analytics_daily',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['website', 'first_seen_at'], name='analytics_v_website_349d56_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['website', 'country_code'], name='analytics_v_website_b6e8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['website', 'device_type'], name='analytics_v_website_f132cc_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['first_seen_at'], name='analytics_v_first_s_8e0b7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('website', 'visitor_hash')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['website', 'started_at'], name='analytics_s_website_8b152d_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['website', 'entry_type'], name='analytics_s_website_b79274_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['visitor', 'started_at'], name='analytics_s_visitor_9a63b9_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['website', 'is_bounce'], name='analytics_s_website_b06449_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['started_at'], name='analytics_s_started_a5739b_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimevisitor',
            index=models.Index(fields=['website', 'last_active_at'], name='analytics_r_website_4ebea2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='realtimevisitor',
            unique_together={('website', 'visitor')},
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'viewed_at'], name='analytics_p_website_b020f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'path'], name='analytics_p_website_5ceb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session', 'viewed_at'], name='analytics_p_session_a37bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['viewed_at'], name='analytics_p_viewed__8f8967_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyanalytics',
            unique_together={('website', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['website', 'event_type', 'occurred_at'], name='analytics_e_website_7e85d6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['website', 'event_name', 'occurred_at'], name='analytics_e_website_9d37b5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['occurred_at'], name='analytics_e_occurre_73cbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['website', 'date'], name='analytics_d_website_c28d15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyanalytics',
            unique_together={('website', 'date')},
        ),
    ]
