# Generated by Django 4.2.30 on 2026-05-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='analytics_e_occurre_485606_idx',
            old_name='analytics_e_occurre_73cbe5_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_p_viewed__a5f8fc_idx',
            old_name='analytics_p_viewed__8f8967_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='analytics_s_started_c4de2d_idx',
            old_name='analytics_s_started_a5739b_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='analytics_v_first_s_f77ff5_idx',
            old_name='analytics_v_first_s_8e0b7b_idx',
        ),
    ]
